Nadia resume
lexemz/Swiftbook-Students-Summaries pull request #1
Opened 2021-09-16 09:58 UTC by NadzeyaShpakouskaya

### Feature: Nadia's resume
**Done:** 
@NadzeyaShpakouskaya 

**Reviewers:**

- @lexemz 
- @ZyFun 
- @ArcaniZZZ

2021-09-16 14:13 UTC, ZyFun requested changes
Во всём коде нашел только лишний импорт фреймворка Foundation

2021-09-16 14:13 UTC, ZyFun commented on Summaries/Models/PersonN.swift
> +import Foundation
Импортировать Фреймворк Foundation здесь не нужно. Он не используется в моделях.

2021-09-16 14:13 UTC, lexemz reviewed
Нашел 3 замечания

2021-09-16 14:13 UTC, lexemz commented on Summaries/Extensions/Extension+UIView.swift
> +//  Extension+UIView.swift
@NadzeyaShpakouskaya файлы не должны же символы содержать в себе (кроме - _)

2021-09-16 14:13 UTC, lexemz commented on Summaries/Extensions/Extension+UITableView.swift
> +//  Extension+UITableView.swift
Символ в имени файлов

2021-09-16 14:13 UTC, lexemz commented on Summaries/ViewControllers/NadiaViewControllers/NadiaShortFormResumeViewController.swift
> +        return 7
ключевое слово return в однострочной функции

2021-09-16 18:45 UTC, ArcaniZZZ reviewed
Ochen nice! Super!

2021-09-17 07:40 UTC, ZyFun approved these changes
Всё хорошо!

2021-09-17 08:56 UTC, merged